name: Generate Keystore
on:
  workflow_dispatch:
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate & Print Keystore
        run: |
          keytool -genkey -v \
            -keystore codenile.jks \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias codenile \
            -storepass StorePass123 \
            -keypass KeyPass123 \
            -dname "CN=CodeNile,O=Dev,C=SD"
          echo "=== COPY THIS ==="
          base64 -w 0 codenile.jks
      - uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: codenile.jks
          retention-days: 1
